
up:
	docker compose up
	
# con nodemon
dev:
	docker compose -f docker-compose-dev.yml up	

build:
	docker compose build

test:
	http GET http://localhost:3000

exec:
	docker-compose exec app /bin/sh










 


